config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :companys
  end
  
  resources :companys do
    resources :departments do
      resources :employees do
        resources :leave_totals
      end
    end
  end

  
  root 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    #has_many :it_licences, through: :departments
    has_many :leave_totals
    belongs_to :department
    validates :first_name, :last_name, :position_title, :gender, :date_of_birth, :employee_hire_date, presence: true
    mount_uploader :employee_photo, EmployeeUploader
    mount_uploader :tax_dec_form, EmployeeUploader
    mount_uploader :super_form, EmployeeUploader
end

app/controllers/employees_controller.rb
class EmployeesController < SessionsController
  
   # Show and edit filter for departments
  before_action :get_employee, only: [:show, :edit, :update, :destroy]
  
  # GET /employees
  def index
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employees = @department.employees.paginate(page: params[:page])
  end

  # GET /employees/:id
  def show
    @department = Department.find(params[:department_id])
  end

  # GET /employees/new
  def new
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employee = Employee.new
  end

  # POST /employees
  def create
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employee = Employee.new(white_listed_parameters)
    if @employee.save
      flash[:notice] = 'Employee Created'
      redirect_to company_department_employees_path(@company, @department)
    else
      render :new
    end
  end

  # GET /employees/:id/edit
  def edit
  end

  # PUT /employees
  def update
    if @employee.update_attributes(white_listed_parameters)
      flash[:notice] = 'Employee saved'
      redirect_to company_department_employees_path
    else
      render :edit
    end
  end

  # DELETE /employees/:id
  def destroy
    @employee.destroy
    flash[:notice] = 'Employee Deleted'
    redirect_to company_department_employees_path
  end

  private

  # Get's the company from the database, and redirects if unable to find one
  def get_employee
    begin
      @company = Company.find(params[:company_id])
      @department = Department.find(params[:department_id])
      @employee = Employee.find(params[:id])
    rescue
      redirect_to company_department_employees_path
    end
  end

  # White lists the corresponding parameters
  def white_listed_parameters
    params
    .require(:employee)
    .permit(:first_name, :last_name, :start_date, :position_title, :gender, :date_of_birth, 
    :address, :suburb, :state, :postcode, :home_phone, :mobile, :email, :tax_file_number, 
    :nok_name, :nok_relationship, :nok_address, :nok_suburb, :nok_state, :nok_postcode,
    :nok_home_phone, :nok_mobile, :nok_work_phone, :employee_hire_date, :employment_status,
    :annual_pay, :monthly_pay, :hourly_rate, :benefits, :bank_name, :bank_branch, :account_name,
    :bsb_number, :account_number, :tax_dec_form, :super_form, :it_licences, :employee_photo, :business_card,
    :annual_leave_allowance, :sick_leave_allowance, :other_leave_allowance,  :country , :nok_country)
    .merge(params.permit(:department_id))
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, url: company_department_employees_path(@company, @department), html: { class: 'well', multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :position_title %>
    <%= f.text_field :position_title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :gender %>
    <%= f.select :gender, [ ['', ''], ['Female', 'Female'], ['Male', 'Male']], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :date_of_birth %>
    <%= f.date_field :date_of_birth, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :suburb %>
    <%= f.text_field :suburb, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :postcode %>
    <%= f.number_field :postcode, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :home_phone %>
    <%= f.telephone_field :home_phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.telephone_field :mobile, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_name, "Next of Kin Name" %>
    <%= f.text_field :nok_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_relationship, "Next of Kin Relationship" %>
    <%= f.text_field :nok_relationship, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_address, "Next of Kin Address" %>
    <%= f.text_field :nok_address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_suburb, "Next of Kin Suburb" %>
    <%= f.text_field :nok_suburb, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_state, "Next of Kin State" %>
    <%= f.text_field :nok_state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_country, "Next of Kin Country" %>
    <%= f.text_field :nok_country, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_postcode, "Next of Kin Postcode/Zipcode" %>
    <%= f.number_field :nok_postcode, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_home_phone, "Next of Kin Home Phone" %>
    <%= f.telephone_field :nok_home_phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_mobile, "Next of Kin Mobile Phone" %>
    <%= f.telephone_field :nok_mobile, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nok_work_phone, "Next of Kin Work Phone" %>
    <%= f.telephone_field :nok_work_phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :employee_hire_date %>
    <%= f.date_field :employee_hire_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :employment_status %>
    <%= f.select :employment_status, [ ['', ''], ['Full Time', 'Full Time'], ['Part Time', 'Part Time'], ['Casual', 'Casual']], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :annual_pay %>
    <%= f.number_field :annual_pay, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :monthly_pay %>
    <%= f.number_field :monthly_pay, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :hourly_rate %>
    <%= f.number_field :hourly_rate, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :benefits %>
    <%= f.text_field :benefits, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :annual_leave_allowance, "Yearly Annual Leave Total (Hours)" %>
    <%= f.number_field :annual_leave_allowance, :value => '160', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sick_leave_allowance, "Yearly Sick Leave Total (Hours)" %>
    <%= f.number_field :sick_leave_allowance, :value => '80', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :other_leave_allowance, "Yearly Other Leave Total (Hours)" %>
    <%= f.number_field :other_leave_allowance, :value => '0', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :tax_file_number %>
    <%= f.number_field :tax_file_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bank_name %>
    <%= f.text_field :bank_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bank_branch %>
    <%= f.text_field :bank_branch, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :account_name %>
    <%= f.text_field :account_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :bsb_number %>
    <%= f.number_field :bsb_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :account_number %>
    <%= f.number_field :account_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Tax Dec Form Submitted" %>
    <%= f.file_field :tax_dec_form, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Super Form Submitted" %>
    <%= f.file_field :super_form, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "IT Licences Processed" %>
    <%= f.check_box :it_licences, {}, true, false %>
  </div>
  <div class="form-group">
    <%= f.label :employee_photo %>
    <%= f.file_field :employee_photo, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label "Business Cards Ordered" %>
    <%= f.check_box :business_card, {}, true, false %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', company_department_employees_path(@company, @department, @employee), class: 'btn btn-info' %>
<% end %>

app/views/employees/edit.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @employee.errors %>
    <div class="col-sm-6">
      <header>
        <h1>Edit Employee Details </h1>
      </header>
      <%= form_for @employee, url: company_department_employee_path(@company, @department, @employee), method: :put, html: { class: 'well', multipart: true } do |f| %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :position_title %>
          <%= f.text_field :position_title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :gender %>
          <%= f.select :gender, [['', ''], ['Female', 'Female'], ['Male', 'Male']], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_of_birth %>
          <%= f.date_field :date_of_birth, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :suburb %>
          <%= f.text_field :suburb, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :state %>
          <%= f.text_field :state, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :country %>
          <%= f.text_field :country, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :postcode %>
          <%= f.number_field :postcode, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :home_phone %>
          <%= f.telephone_field :home_phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :mobile %>
          <%= f.telephone_field :mobile, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_name, "Next of Kin Name" %>
          <%= f.text_field :nok_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_relationship, "Next of Kin Relationship" %>
          <%= f.text_field :nok_relationship, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_address, "Next of Kin Address" %>
          <%= f.text_field :nok_address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_suburb, "Next of Kin Suburb" %>
          <%= f.text_field :nok_suburb, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_state, "Next of Kin State" %>
          <%= f.text_field :nok_state, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_country, "Next of Kin Country" %>
          <%= f.text_field :nok_country, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_postcode, "Next of Kin Postcode" %>
          <%= f.number_field :nok_postcode, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_home_phone, "Next of Kin Home Phone" %>
          <%= f.telephone_field :nok_home_phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_mobile, "Next of Kin Mobile Phone" %>
          <%= f.telephone_field :nok_mobile, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nok_work_phone, "Next of Kin Work Phone" %>
          <%= f.telephone_field :nok_work_phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :employee_hire_date %>
          <%= f.date_field :employee_hire_date, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :employment_status %>
          <%= f.select :employment_status, [['', ''], ['Full Time', 'Full Time'], ['Part Time', 'Part Time'], ['Casual', 'Casual']], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :annual_pay %>
          <%= f.number_field :annual_pay, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :monthly_pay %>
          <%= f.number_field :monthly_pay, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :hourly_rate %>
          <%= f.number_field :hourly_rate, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :benefits %>
          <%= f.text_field :benefits, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :annual_leave_allowance, "Yearly Annual Leave Total (Hours)" %>
          <%= f.number_field :annual_leave_allowance, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :sick_leave_allowance, "Yearly Sick Leave Total (Hours)" %>
          <%= f.number_field :sick_leave_allowance, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :other_leave_allowance, "Yearly Other Leave Total (Hours)" %>
          <%= f.number_field :other_leave_allowance, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :tax_file_number %>
          <%= f.number_field :tax_file_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :bank_name %>
          <%= f.text_field :bank_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :bank_branch %>
          <%= f.text_field :bank_branch, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :account_name %>
          <%= f.text_field :account_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :bsb_number %>
          <%= f.number_field :bsb_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :account_number %>
          <%= f.number_field :account_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "Tax Dec Form Submitted" %>
          <%= f.file_field :tax_dec_form, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "Super Form Submitted" %>
          <%= f.file_field :super_form, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "IT Licences Processed" %> <br />
          <%= f.check_box :it_licences, {}, true, false %> <br />
        </div>
        <div class="form-group">
          <%= f.label :employee_photo %>
          <%= f.file_field :employee_photo, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "Business Cards Ordered" %> <br />
          <%= f.check_box :business_card, {}, true, false %> <br />
        </div>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', company_department_employees_path(@company, @department, @employee), class: 'btn btn-info' %>
      <% end %>
    </div>
</div>

app/views/employees/index.html.erb
<h1 class="page-header"><%= "#{@department.department_name}" %></h1>
<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <thead>
      <tr>
        <th>Employee Name</th>
        <th>Position</th>
        <th>Start Date</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= link_to "#{employee.first_name}"" ""#{employee.last_name}", company_department_employee_path(@company, @department, employee) %></td>
          <td><%= employee.position_title %></td>
          <td><%= employee.employee_hire_date %></td>
          <td><%= link_to 'Manage Employee Leave', company_department_employee_leave_totals_path(@company, @department, employee) %></td>
          <td>
            <i class="fa fa-<%= employee.gender.downcase %>"></i>
          </td>
          <td>
            <%= link_to 'Edit', edit_company_department_employee_path(@company, @department, employee) %>&nbsp;
            <%= link_to 'Delete', company_department_employee_path(@company, @department, employee), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @employees %><br>

<%= link_to "Add Employee", new_company_department_employee_path, class: 'btn btn-primary' %>
<%= link_to "Back to Departments", company_departments_path(@company, @department), class: 'btn btn-info' %>

app/views/employees/new.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @employee.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Add New Employee </h1>
    </header>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/employees/show.html.erb
<h1 class="page-header"><%= "#{@employee.first_name}"" ""#{@employee.last_name}" %></h1>
<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <tbody>
        <tr>
          <td>First Name</td>
          <td><%= @employee.first_name %></td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td><%= @employee.last_name %></td>
        </tr>
        <tr>
          <td>Position</td>
          <td><%= @employee.position_title %></td>
        </tr>
        <tr>
          <td>Gender</td>
          <td><%= @employee.gender %></td>
        </tr>
        <tr>
          <td>Date of Birth</td>
          <td><%= @employee.date_of_birth %></td>
        </tr>
        <tr>
          <td>Address</td>
          <td><%= @employee.address %></td>
        </tr>
        <tr>
          <td>Suburb</td>
          <td><%= @employee.suburb %></td>
        </tr>
        <tr>
          <td>State</td>
          <td><%= @employee.state %></td>
        </tr>
        <tr>
          <td>Country</td>
          <td><%= @employee.country %></td>
        </tr>
        <tr>
          <td>Postcode</td>
          <td><%= @employee.postcode %></td>
        </tr>
        <tr>
          <td>Home Phone</td>
          <td><%= @employee.home_phone %></td>
        </tr>
        <tr>
          <td>Mobile</td>
          <td><%= @employee.mobile %></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%= @employee.email %></td>
        </tr>
        <tr>
          <td>Next of Kin</td>
          <td><%= @employee.nok_name %></td>
        </tr>
        <tr>
          <td>Next of Kin Relationship</td>
          <td><%= @employee.nok_relationship %></td>
        </tr>
        <tr>
          <td>Next of Kin Address</td>
          <td><%= @employee.nok_address %></td>
        </tr>
        <tr>
          <td>Next of Kin Suburb</td>
          <td><%= @employee.nok_suburb %></td>
        </tr>
        <tr>
          <td>Next of Kin State</td>
          <td><%= @employee.nok_state %></td>
        </tr>
        <tr>
          <td>Next of Kin Country</td>
          <td><%= @employee.nok_country %></td>
        </tr>
        <tr>
          <td>Next of Kin Postcode</td>
          <td><%= @employee.nok_postcode %></td>
        </tr>
        <tr>
          <td>Next of Kin Home Phone</td>
          <td><%= @employee.nok_home_phone %></td>
        </tr>
        <tr>
          <td>Next of Kin Mobile Phone</td>
          <td><%= @employee.nok_mobile %></td>
        </tr>
        <tr>
          <td>Next of Kin Work Phone</td>
          <td><%= @employee.nok_work_phone %></td>
        </tr>
        <tr>
          <td>Hire Date</td>
          <td><%= @employee.employee_hire_date %></td>
        </tr>
        <tr>
          <td>Employment Status</td>
          <td><%= @employee.employment_status %></td>
        </tr>
        <tr>
          <td>Annual Pay</td>
          <td><%= @employee.annual_pay %></td>
        </tr>
        <tr>
          <td>Monthly Pay</td>
          <td><%= @employee.monthly_pay %></td>
        </tr>
        <tr>
          <td>Hourly Rate</td>
          <td><%= @employee.hourly_rate %></td>
        </tr>
        <tr>
          <td>Benefits</td>
          <td><%= @employee.benefits %></td>
        </tr>
        <tr>
          <td>Yearly Annual Leave Total (Hours)</td>
          <td><%= @employee.annual_leave_allowance %></td>
        </tr>
        <tr>
          <td>Yearly Sick Leave Total (Hours)</td>
          <td><%= @employee.sick_leave_allowance %></td>
        </tr>
        <tr>
          <td>Yearly Other Leave Total (Hours)</td>
          <td><%= @employee.other_leave_allowance %></td>
        </tr>
        <tr>
          <td>Tax File Number</td>
          <td><%= @employee.tax_file_number %></td>
        </tr>
        <tr>
          <td>Bank Name</td>
          <td><%= @employee.bank_name %></td>
        </tr>
        <tr>
          <td>Bank Branch</td>
          <td><%= @employee.bank_branch %></td>
        </tr>
        <tr>
          <td>Account Name</td>
          <td><%= @employee.account_name %></td>
        </tr>
        <tr>
          <td>BSB Number</td>
          <td><%= @employee.bsb_number %></td>
        </tr>
        <tr>
          <td>Account Number</td>
          <td><%= @employee.account_number %></td>
        </tr>
        <tr>
          <td>Tax Dec Form Submitted?</td>
          <td><%= @employee.tax_dec_form %></td>
        </tr>
        <tr>
          <td>Super Form Submitted?</td>
          <td><%= @employee.super_form %></td>
        </tr>
        <tr>
          <td>IT Licences Processed</td>
          <td><%= @employee.it_licences %></td>
        </tr>
        <tr>
          <td>Employee Photo</td>
          <td><%= image_tag(@employee.employee_photo.url) %></td>
        </tr>
        <tr>
          <td>Business Cards Processed</td>
          <td><%= @employee.business_card %></td>
        </tr>
    </tbody>
  </table>
</div> 
<%= link_to 'Edit', edit_company_department_employee_path(@company, @department, @employee), class: 'btn btn-primary' %>
<%= link_to 'Back', company_department_employees_path(@company, @department, @employee), class: 'btn btn-info' %>