config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :companys
  end
  
  resources :companys do
    resources :departments do
      resources :employees do
        resources :leave_totals
      end
    end
  end

  
  root 'home#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
    belongs_to :company
    has_many :employees
    has_many :leave_totals, :through => :employees
    validates :department_name, presence: true
    
end

app/controllers/departments_controller.rb
class DepartmentsController < SessionsController
  
  # Show and edit filter for departments
  before_action :get_department, only: [:show, :edit, :update, :destroy]
  
  # GET /departments
  def index
    @company = Company.find(params[:company_id])
    @departments = @company.departments.paginate(page: params[:page])
  end

  # GET /departments/:id
  def show
  end

  # GET /departments/new
  def new
    @company = Company.find(params[:company_id])
    @department = Department.new
  end

  # POST /departments
  def create
    @company = Company.find(params[:company_id])
    @department = Department.new(white_listed_parameters)
    if @department.save
      flash[:notice] = 'Department Created'
      redirect_to company_departments_path(@company)
    else
      render :new
    end
  end

  # GET /departments/:id/edit
  def edit
    
  end

  # PUT /departments
  def update
    if @department.update_attributes(white_listed_parameters)
      flash[:notice] = 'Department saved'
      puts "it got into saving it"
      redirect_to company_departments_path
    else
      render :edit
    end
  end

  # DELETE /companys/:id
  def destroy
    @department.destroy
    redirect_to company_departments_path
  end

  private

  # Get's the company from the database, and redirects if unable to find one
  def get_department
    begin
      @company = Company.find(params[:company_id])
      @department = @company.departments.find(params[:id])
    rescue
      redirect_to departments_path
    end
  end

  # White lists the corresponding parameters
  def white_listed_parameters
    params
    .require(:department)
    .permit(:department_name)
    .merge(params.permit(:company_id))
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department, url: company_departments_path(@company), html: { class: 'well' } do |f| %>
  <div class="form-group">
    <%= f.label :department_name %>
    <%= f.text_field :department_name, class: 'form-control' %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to "Cancel", company_departments_path(@company, @department), class: 'btn btn-info' %>
<% end %>

app/views/departments/edit.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @department.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Edit <%= @department.department_name %> Department </h1>
    </header>
    <%= form_for @department, url: company_department_path(@company, @department), method: :put, html: { class: 'well' } do |f| %>
      <div class="form-group">
        <%= f.label :department_name %>
        <%= f.text_field :department_name, class: 'form-control' %>
      </div>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to "Cancel", company_departments_path(@company, @department), class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/departments/index.html.erb
<h1 class="page-header"><%= "#{@company.company_name}" %></h1>
<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <thead>
      <tr>
        <th>Departments</th>
      </tr>
    </thead>
    <tbody>
      <% @departments.each do |department| %>
        <tr>
          <td><%= link_to department.department_name, company_department_employees_path(@company, department, @employees) %></td>
          <td>
            <%= link_to 'Edit', edit_company_department_path(@company, department) %>&nbsp;
            <%= link_to 'Delete', company_department_path(@company, department), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @departments %><br>
<%= link_to "Add Department", new_company_department_path(@company), class: 'btn btn-primary' %>
<%= link_to "Back to Company Home", companys_path(@company), class: 'btn btn-info' %>

app/views/departments/new.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @department.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Add New Department </h1>
    </header>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/departments/show.html.erb
<div class="page-header">
  <h1>
    <%= @department.department_name %>
  </h1>
  <%= link_to "Back to Departments", company_departments_path(@company, @department), class: 'btn btn-info' %>
</div>