config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :companys
  end
  
  resources :companys do
    resources :departments do
      resources :employees do
        resources :leave_totals
      end
    end
  end

  
  root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :users
    has_many :departments
    has_many :employees, through: :departments
    validates :company_name, presence: true
    #validates_presence_of :company_avatar, :content_type => /\Aimage\/.*\Z/
    mount_uploader :company_avatar, CompanyAvatarUploader
    
end

app/controllers/companys_controller.rb
class CompanysController < SessionsController
  
  # Show and edit filter for companys
  before_action :get_company, only: [ :show, :edit, :update, :destroy]
  
# GET /companys
  def index
    @companys = [current_user.company]
  end

  # GET /companys/:id
  def show
  end

  # GET /companys/new
  def new
    @company = Company.new
  end

  # POST /companys
  def create
    @company = Company.new(white_listed_parameters)
    if @company.save
      flash[:notice] = 'Company Created'
      redirect_to companys_path
    else
      render :new
    end
  end

  # GET /companys/:id/edit
  def edit
  end

  # PUT /companys
  def update
    if @company.update_attributes(white_listed_parameters)
      flash[:notice] = 'Company saved'
      redirect_to companys_path
    else
      render :edit
    end
  end

  # DELETE /companys/:id
  def destroy
    @company.destroy
    redirect_to companys_path
  end

  private

  # Get's the company from the database, and redirects if unable to find one
  def get_company
    begin
      @company = Company.find(params[:id])
    rescue
      redirect_to companys_path
    end
  end

  # White lists the corresponding parameters
  def white_listed_parameters
    params
      .require(:company)
      .permit(:company_name, :company_avatar)
  end
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/views/companys/edit.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @company.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Edit <%= @company.company_name  %> Company</h1>
    </header>
  <%= form_for @company, html: {class: 'well', multipart: true}  do |f| %>
    <div class="form-group">
      <%= f.label :company_name %>
      <%= f.text_field :company_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :company_avatar %>
      <%= f.file_field :company_avatar, class: 'form-control' %>
    </div>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to "Cancel", companys_path(@company), class: 'btn btn-info' %>
  <% end %>
  </div>
</div>

app/views/companys/index.html.erb
<h1 class="page-header">Company Home</h1>
<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <thead>
      <tr>
        <th>Company</th>
        <th>Departments</th>
      </tr>
    </thead>
    <tbody>
      <% @companys.each do |company| %>
        <tr>
          <td><%= link_to company.company_name, company %></td>
          <td><%= link_to "#{company.company_name} Departments", company_departments_path(company) %></td>
          <td>
            <%= link_to 'Edit', edit_company_path(company) %>&nbsp;
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/companys/new.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @company.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Add New Company</h1>
    </header>
  <%= form_for @company, url: {action: "create"}, html: {class: 'well'} do |f| %>
    <div class="form-group">
      <%= f.label :company_name %>
      <%= f.text_field :company_name, class: 'form-control' %>
    </div>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to "Cancel", companys_path(@company), class: 'btn btn-info' %>
  <% end %>
  </div>
</div>

app/views/companys/show.html.erb
<div class="page-header">
  <h1>
    <%= @company.company_name %>
  </h1>
  <div>
    <tbody>
      <tr>
          <%= image_tag(@company.company_avatar.url) %>
      </tr>
    </tbody>
  </div>
  <div>
    <tbody>
      <tr>
      </tr>
    </tbody>
  </div>
  <div>
    <tbody>
      <tr>
          <%= link_to "#{@company.company_name} Departments", company_departments_path(@company), class: 'btn btn-primary' %>
          <%= link_to "Back to Company Home", companys_path(@company), class: 'btn btn-info' %>
      </tr>
    </tbody>
  </div>
</div>