config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do
    resources :companys
  end
  
  resources :companys do
    resources :departments do
      resources :employees do
        resources :leave_totals
      end
    end
  end

  
  root 'home#index'

end

app/models/leave_total.rb
class LeaveTotal < ActiveRecord::Base
    belongs_to :employee
    validates :annual_leave, :sick_leave, :other_leave, :reasons_for_leave, :date_leave_requested, presence: true
end

app/controllers/leave_totals_controller.rb
class LeaveTotalsController < SessionsController
 
   # Show and edit filter for departments
  before_action :get_leave_total, only: [:show, :edit, :update, :destroy]
  
  # GET /leave totals
  def index
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employee = Employee.find(params[:employee_id])
    @leave_totals = @employee.leave_totals.paginate(page: params[:page])
  end

  # GET /leave totals/:id
  def show
  end

  # GET /leave totals/new
  def new
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employee = Employee.find(params[:employee_id])
    @leave_total = LeaveTotal.new
  end

  # POST /leave totals
  def create
    @company = Company.find(params[:company_id])
    @department = Department.find(params[:department_id])
    @employee = Employee.find(params[:employee_id])
    @leave_total = LeaveTotal.new(white_listed_parameters)
    @leave_total.employee = @employee
    if @leave_total.save
      flash[:notice] = 'Leave Logged'
      redirect_to company_department_employee_leave_totals_path(@company, @department, @employee)
    else
      render :new
    end
  end

  # GET /leave totals/:id/edit
  def edit
  end

  # PUT /leave totals
  def update
    @leave_total.employee = @employee
    if @leave_total.update_attributes(white_listed_parameters)
      flash[:notice] = 'Leave Logged'
      redirect_to company_department_employee_leave_totals_path
    else
      render :edit
    end
  end

  # DELETE /leave totals/:id
  def destroy
    @leave_total.destroy
    redirect_to company_department_employee_leave_totals_path
  end

  private

  # Get's the leave_total from the database, and redirects if unable to find one
  def get_leave_total
    begin
      @company = Company.find(params[:company_id])
      @department = Department.find(params[:department_id])
      @employee = Employee.find(params[:employee_id])
      @leave_total = LeaveTotal.find(params[:id])
    rescue
      redirect_to company_department_employee_leave_totals_path
    end
  end

  # White lists the corresponding parameters
  def white_listed_parameters
    params
    .require(:leave_total)
    .permit(:annual_leave, :sick_leave, :other_leave, :reasons_for_leave, :date_leave_requested)
    .merge(params.permit(:employee_id))
  end
  
  
  def remaining_annual_leave(employee, leave_totals)
        @leave_totals = @employee.leave_totals
        annual_leave_total = 0
        @leave_totals.each do |leave_total|
            annual_leave_total = annual_leave_total + leave_total.annual_leave
        end
        @employee.annual_leave_allowance - annual_leave_total
  end
    
  def remaining_sick_leave(employee, leave_totals)
      @leave_totals = @employee.leave_totals
      sick_leave_total = 0
      leave_totals.each do |leave_total|
          sick_leave_total = sick_leave_total + leave_total.sick_leave
      end
      @employee.sick_leave_allowance - sick_leave_total
  end
    
  def remaining_other_leave(employee, leave_totals)
      @leave_totals = @employee.leave_totals
      other_leave_total = 0
      leave_totals.each do |leave_total|
          other_leave_total = other_leave_total + leave_total.other_leave
      end
      @employee.other_leave_allowance - other_leave_total
  end
  

end

app/helpers/leave_totals_helper.rb
module LeaveTotalsHelper
    def remaining_annual_leave(employee, leave_totals)
        annual_leave_total = 0
        leave_totals.each do |leave_total|
            annual_leave_total = annual_leave_total + leave_total.annual_leave
        end
        @employee.annual_leave_allowance - annual_leave_total
    end
    
    def remaining_sick_leave(employee, leave_totals)
        sick_leave_total = 0
        leave_totals.each do |leave_total|
            sick_leave_total = sick_leave_total + leave_total.sick_leave
        end
        @employee.sick_leave_allowance - sick_leave_total
    end
    
    def remaining_other_leave(employee, leave_totals)
        other_leave_total = 0
        leave_totals.each do |leave_total|
            other_leave_total = other_leave_total + leave_total.other_leave
        end
        @employee.other_leave_allowance - other_leave_total
    end
    
end

app/views/leave_totals/edit.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @leave_total.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Edit Leave Details </h1>
    </header>
  <%= form_for @leave_total, url: company_department_employee_leave_total_path(@company, @department, @employee, @leave_total), html: { class: 'well', multipart: true } do |f| %>
        <div class="form-group">
          <%= f.label :reasons_for_leave, "Reason for Leave" %>
          <%= f.text_field :reasons_for_leave, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_leave_requested, "Date Leave Requested" %>
          <%= f.date_field :date_leave_requested, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :annual_leave, "Annual Leave Hours to be Taken" %>
          <%= f.number_field :annual_leave, :value => '0', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :sick_leave, "Sick Leave Hours to be Taken" %>
          <%= f.number_field :sick_leave, :value => '0', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :other_leave, "Other Leave Hours to be Taken" %>
          <%= f.number_field :other_leave, :value => '0', class: 'form-control' %>
        </div>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', company_department_employee_leave_totals_path(@company, @department, @employee), class: 'btn btn-info' %>
  <% end %>
  </div>
</div>

app/views/leave_totals/index.html.erb
<h1 class="page-header"><%= "#{@employee.first_name}"" ""#{@employee.last_name}" %> Leave Log</h1>

<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <thead>
      <tr>
        <th>Remaining Annual Leave (Hours)</th>
        <th>Remaining Sick Leave (Hours)</th>
        <th>Remaining Other Leave (Hours)</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= remaining_annual_leave(@employee, @leave_totals) %></td>
          <td><%= remaining_sick_leave(@employee, @leave_totals) %></td>
          <td><%= remaining_other_leave(@employee, @leave_totals).to_i %></td>
        </tr>
    </tbody>
  </table>
</div>

<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <thead>
      <tr>
        <th>Reason Leave Taken</th>
        <th>Date Leave Requested</th>
        <th>Annual Leave Taken</th>
        <th>Sick Leave Taken</th>
        <th>Other Leave Taken</th>
      </tr>
    </thead>
    <tbody>
      <% @leave_totals.each do |leave_total| %>
        <tr>
          <td><%= leave_total.reasons_for_leave %></td>
          <td><%= leave_total.date_leave_requested %></td>
          <td><%= leave_total.annual_leave %></td>
          <td><%= leave_total.sick_leave %></td>
          <td><%= leave_total.other_leave %></td>
          <td><%= link_to 'Edit', edit_company_department_employee_leave_total_path(@company, @department, @employee, leave_total) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @leave_totals %><br>
<%= link_to 'Log Leave', new_company_department_employee_leave_total_path(@company, @department, @employee, @leave_total), class: 'btn btn-primary' %>
<%= link_to 'Back to Employees', company_department_employees_path(@company, @department, @employee), class: 'btn btn-info' %>

app/views/leave_totals/new.html.erb
<div class="row">
  <%= render partial: 'shared/errors', object: @leave_total.errors %>
  <div class="col-sm-6">
    <header>
      <h1>Log Leave </h1>
    </header>
  <%= form_for @leave_total, url: company_department_employee_leave_totals_path(@company, @department, @employee), html: { class: 'well', multipart: true } do |f| %>
        <div class="form-group">
          <%= f.label :reasons_for_leave, "Reason for Leave" %>
          <%= f.text_field :reasons_for_leave, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_leave_requested, "Date Leave Requested" %>
          <%= f.date_field :date_leave_requested, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :annual_leave, "Annual Leave Hours to be Taken" %>
          <%= f.number_field :annual_leave, :value => '0', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :sick_leave, "Sick Leave Hours to be Taken" %>
          <%= f.number_field :sick_leave, :value => '0', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :other_leave, "Other Leave Hours to be Taken" %>
          <%= f.number_field :other_leave, :value => '0', class: 'form-control' %>
        </div>
        <%= f.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', company_department_employee_leave_totals_path(@company, @department, @employee), class: 'btn btn-info' %>
  <% end %>
  </div>
</div>

app/views/leave_totals/show.html.erb
<h1 class="page-header"><%= "#{@employee.first_name}"" ""#{@employee.last_name}" "Leave Details"%></h1>
<div class="table-responsive">
  <table class="table table-striped" role="grid">
    <tbody>
        <tr>
          <td>Reason for Leave</td>
          <td><%= @leave_total.reasons_for_leave %></td>
        </tr>
        <tr>
          <td>Date Leave Requested</td>
          <td><%= @leave_total.date_leave_requested %></td>
        </tr>
        <tr>
          <td>Annual Leave Requested (Hours)</td>
          <td><%= @leave_total.annual_leave %></td>
        </tr>
        <tr>
          <td>Sick Leave Requested (Hours)</td>
          <td><%= @leave_total.sick_leave %></td>
        </tr>
        <tr>
          <td>Other Leave Requested (Hours)</td>
          <td><%= @leave_total.other_leave %></td>
        </tr>
        </tbody>
  </table>
</div>